### ISSUE TITLE
Please use .gitignore !

### ISSUE THREAD

**Issue by KuroLycan** [anand9752/Backend#1]
Hey Anand  I am going through your repo and it has the .env files which contains your  "SECRET KEYS" . Please use a .gitignore file to ignore them and also node_modules folder has a lot of stuff so excluse them too . You can refer to this Documentation for https://git-scm.com/docs/gitignore

**Comment by anand9752** [comment]
Thank You Krishna , i deleted .evn file from my github repo , instead of using gitignore
